version: 2.1
jobs:

  # cloud - production
  builtwithconnect-com-functions:
    executor: functions
    steps:
      - functions:
          project: connect-report-app

  builtwithconnect-com-hosting:
    executor: hosting
    steps:
      - hosting:
          project: connect-report-app

executors:
      
  functions:
    docker:
      - image: cimg/node:18.16-browsers
    resource_class: large
    working_directory: ~/connect/standalone/functions

  hosting:
    docker:
      - image: cimg/node:18.16-browsers
    resource_class: large
    working_directory: ~/connect/standalone

commands:

  prepare:
    steps:
      - checkout:
          path: ~/connect

      - run:
          name: Setup environment
          command: |
            npm install --prefix=$HOME/.local yarn@berry -g
            yarn --version

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "~/connect/yarn.lock" }}
      - run: 
          name: Install dependencies
          command: |
            (cd ~/connect && yarn install --immutable)

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "~/connect/yarn.lock" }}
          paths:
            - ~/connect/.yarn/cache
            - ~/connect/.yarn/unplugged

  functions:
    parameters:
      project:
        type: string
    steps:
      - prepare

      - run:
          name: Deploy firebase functions
          command: yarn run firebase deploy -f --only functions --project << parameters.project >>

  hosting:
    parameters:
      project:
        type: string
    steps:
      - prepare
      
      - run:
          name: Deploy firebase hosting & database
          command: |
            export NODE_ENV=production
            yarn build
            yarn run firebase deploy -f --only hosting --project << parameters.project >>

workflows:
  deploy:
    jobs:
      # Cloud - Production
      - builtwithconnect-com-functions:
          filters:
            branches:
              only: main
      - builtwithconnect-com-hosting:
          requires:
            - builtwithconnect-com-functions
          filters:
            branches:
              only: main
